package graphic;

import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;

import correios.util.Agencia;
import correios.util.Encomenda;

/**
 * @author Vinícius Souza
 */
public class NovaEncomenda extends javax.swing.JFrame {

	private String nomeUsuario;
	private Agencia agencia;
	private boolean registrada=false;
	private boolean expressa=false;
    /** Creates new form NovaEncomenda */
    public NovaEncomenda(String nomeUsuario) {
        initComponents();
        this.nomeUsuario=nomeUsuario;
        agencia = new Agencia(nomeUsuario);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(254, 254, 164));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18));
        jLabel1.setForeground(new java.awt.Color(28, 35, 129));
        jLabel1.setText("Nova Encomenda");

        jTextField1.setBackground(new java.awt.Color(228, 233, 65));
        jTextField1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(29, 20, 142));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("CEP do remetente");
        jTextField1.setPreferredSize(new java.awt.Dimension(150, 25));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickCep1(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                checarValores(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(228, 233, 65));
        jTextField2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(29, 20, 142));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("CEP do destinatario");
        jTextField2.setPreferredSize(new java.awt.Dimension(150, 25));
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickCep2(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                checar(evt);
            }
        });

        jTextField3.setBackground(new java.awt.Color(228, 233, 65));
        jTextField3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(29, 20, 142));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Cidade");
        jTextField3.setPreferredSize(new java.awt.Dimension(150, 25));
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickCidade(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                checar(evt);
            }
        });

        jTextField4.setBackground(new java.awt.Color(228, 233, 65));
        jTextField4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(29, 20, 142));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Estado");
        jTextField4.setPreferredSize(new java.awt.Dimension(150, 25));
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickEstado(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                checar(evt);
            }
        });

        jTextField5.setBackground(new java.awt.Color(228, 233, 65));
        jTextField5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(29, 20, 142));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("peso (em gramas)");
        jTextField5.setPreferredSize(new java.awt.Dimension(150, 25));
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickPeso(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(18, 14, 137));
        jLabel2.setFont(new java.awt.Font("Verdana", 0, 13));
        jLabel2.setForeground(new java.awt.Color(29, 40, 153));
        jLabel2.setText("Os campos numericos");

        jLabel3.setBackground(new java.awt.Color(18, 14, 137));
        jLabel3.setFont(new java.awt.Font("Verdana", 0, 13));
        jLabel3.setForeground(new java.awt.Color(29, 40, 153));
        jLabel3.setText("devem conter apenas ");

        jLabel4.setBackground(new java.awt.Color(18, 14, 137));
        jLabel4.setFont(new java.awt.Font("Verdana", 0, 13));
        jLabel4.setForeground(new java.awt.Color(29, 40, 153));
        jLabel4.setText("numeros.");

        jButton1.setBackground(new java.awt.Color(228, 233, 65));
        jButton1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(40, 39, 123));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaEncomenda(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(228, 233, 65));
        jButton2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(40, 39, 123));
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar(evt);
            }
        });

        jCheckBox1.setText("Encomenda expressa");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressa(evt);
            }
        });

        jCheckBox2.setText("Encomenda registrada");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrada(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(18, 14, 137));
        jLabel5.setForeground(new java.awt.Color(29, 40, 153));
        jLabel5.setText("Caso a encomenda tenha");

        jLabel6.setBackground(new java.awt.Color(18, 14, 137));
        jLabel6.setForeground(new java.awt.Color(29, 40, 153));
        jLabel6.setText("peso ou valor declarado");

        jLabel7.setBackground(new java.awt.Color(18, 14, 137));
        jLabel7.setForeground(new java.awt.Color(29, 40, 153));
        jLabel7.setText("acima do limite, sera");

        jLabel8.setBackground(new java.awt.Color(18, 14, 137));
        jLabel8.setForeground(new java.awt.Color(29, 40, 153));
        jLabel8.setText("automaticamente expressa.");

        jTextField6.setText("valor declarado");
        jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickValorDeclarado(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                checar(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel1)
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void cancelar(java.awt.event.ActionEvent evt) {                          
        setVisible(false);
        (new MenuEncomenda(nomeUsuario)).setVisible(true);
    }                         

    private void novaEncomenda(java.awt.event.ActionEvent evt) {
    	boolean valor = false;
        try {
        	double valorDeclarado = Double.parseDouble(jTextField6.getText());
        	valor=true;
        } catch (Exception e) {
		}
        
        if (valor) {
        	if (expressa) {
        		agencia.addEncomenda(agencia.criaEncomendaExpressa(jTextField1.getText(), jTextField2.getText(), (new SimpleDateFormat("ddMMyyyy").format((new GregorianCalendar()).getTime())), nomeUsuario, jTextField3.getText(), jTextField4.getText(), Double.parseDouble(jTextField5.getText()), Double.parseDouble(jTextField6.getText())));
        		return;
        	} else if (registrada){
        		agencia.addEncomenda(agencia.criaEncomendaRegistrada(jTextField1.getText(), jTextField2.getText(), (new SimpleDateFormat("ddMMyyyy").format((new GregorianCalendar()).getTime())), nomeUsuario, jTextField3.getText(), jTextField4.getText(), Double.parseDouble(jTextField5.getText()), Double.parseDouble(jTextField6.getText())));
        		return;
        	} else {
        		agencia.addEncomenda(agencia.criaEncomendaSimples(jTextField1.getText(), jTextField2.getText(), (new SimpleDateFormat("ddMMyyyy").format((new GregorianCalendar()).getTime())), nomeUsuario, jTextField3.getText(), jTextField4.getText(), Double.parseDouble(jTextField5.getText()), Double.parseDouble(jTextField6.getText())));
        	}
        	
        } else {
        	if (expressa) {
        		agencia.addEncomenda(agencia.criaEncomendaExpressa(jTextField1.getText(), jTextField2.getText(), (new SimpleDateFormat("ddMMyyyy").format((new GregorianCalendar()).getTime())), nomeUsuario, jTextField3.getText(), jTextField4.getText(), Double.parseDouble(jTextField5.getText())));
        		return;
        	} else if (registrada){
        		agencia.addEncomenda(agencia.criaEncomendaRegistrada(jTextField1.getText(), jTextField2.getText(), (new SimpleDateFormat("ddMMyyyy").format((new GregorianCalendar()).getTime())), nomeUsuario, jTextField3.getText(), jTextField4.getText(), Double.parseDouble(jTextField5.getText())));
        		return;
        	} else {
        		agencia.addEncomenda(agencia.criaEncomendaSimples(jTextField1.getText(), jTextField2.getText(), (new SimpleDateFormat("ddMMyyyy").format((new GregorianCalendar()).getTime())), nomeUsuario, jTextField3.getText(), jTextField4.getText(), Double.parseDouble(jTextField5.getText())));
        	}
        }
    }                              

    private void checarValores(java.awt.event.KeyEvent evt) {
    }

    private void clickCep1(java.awt.event.MouseEvent evt) {
    	if (jTextField1.isCursorSet() && jTextField1.getText().equals("CEP do remetente")) {
    		jTextField1.setText("");
    	}
    }

    private void clickCep2(java.awt.event.MouseEvent evt) {
    	if (jTextField2.isCursorSet() && jTextField2.getText().equals("CEP do destinatario")) {
    		jTextField2.setText("");
    	}
    }

    private void checar(java.awt.event.KeyEvent evt) {
        //cep 1,2
    	String check = "";
    	for (String s: jTextField1.getText().split("")) {
    		if (s.matches("[0-9]")) {
    			check+=s;
    		}
    	}
    	jTextField1.setText(check);
    	
    	check = "";
    	for (String s: jTextField2.getText().split("")) {
    		if (s.matches("[0-9]")) {
    			check+=s;
    		}
    	}
    	jTextField2.setText(check);
    	
    	check = "";
    	for (String s: jTextField3.getText().split("")) {
    		if (s.toLowerCase().matches("[a-z]")) {
    			check+=s;
    		}
    	}
    	jTextField3.setText(check);
    	
    	check = "";
    	for (String s: jTextField4.getText().split("")) {
    		if (s.toLowerCase().matches("[a-z]")) {
    			check+=s;
    		}
    	}
    	jTextField4.setText(check);
    	
    	check = "";
    	for (String s: jTextField5.getText().split("")) {
    		if (s.matches("[0-9]") || s.equals(".")) {
    			check+=s;
    		}
    	}
    	jTextField5.setText(check);
    	
    	check = "";
    	for (String s: jTextField6.getText().split("")) {
    		if (s.matches("[0-9]") || s.equals(".")) {
    			check+=s;
    		}
    	}
    	jTextField6.setText(check);
    }

    private void clickCidade(java.awt.event.MouseEvent evt) {
    	if (jTextField3.isCursorSet() && jTextField3.getText().equals("Cidade")) {
    		jTextField3.setText("");
    	}
    }

    private void clickEstado(java.awt.event.MouseEvent evt) {
    	if (jTextField4.isCursorSet() && jTextField4.getText().equals("Estado")) {
    		jTextField4.setText("");
    	}
    }

    private void clickPeso(java.awt.event.MouseEvent evt) {
    	if (jTextField5.isCursorSet() && jTextField5.getText().equals("peso (em gramas)")) {
    		jTextField5.setText("");
    	}
    }

    private void expressa(java.awt.event.ActionEvent evt) {
    	expressa=!expressa;
    	if (expressa) {
    		registrada=true;
    		jCheckBox1.setSelected(expressa);
    		jCheckBox2.setSelected(registrada);
    	}
    }

    private void registrada(java.awt.event.ActionEvent evt) {
        if (!expressa) {
        	registrada=!registrada;
        	jCheckBox2.setSelected(registrada);        	
        }
    }

    private void clickValorDeclarado(java.awt.event.MouseEvent evt) {
    	if (jTextField6.isCursorSet() && jTextField6.getText().equals("valor declarado")) {
    		jTextField6.setText("");
    	}
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovaEncomenda("asdf").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration

}

